
version: '3.8'

services:
  mongo1:
    image: mongo
    container_name: mongo1
    restart: always
    ports:
      - "127.0.10.1:27017:27017"
    volumes:
      - ./mongo1:/data/db
    command: mongod --replSet my-mongo-set --bind_ip_all

  mongo2:
    image: mongo
    container_name: mongo2
    restart: always
    ports:
      - "127.0.20.1:27017:27017"
    volumes:
      - ./mongo2:/data/db
    command: mongod --replSet my-mongo-set --bind_ip_all
  mongo3:
    image: mongo
    container_name: mongo3
    restart: always
    ports:
      - "127.0.30.1:27017:27017"
    volumes:
      - ./mongo3:/data/db
    command: mongod --replSet my-mongo-set --bind_ip_all

#   mongoinit:
#     image: mongo

#     container_name: mongoinit
#     restart: always
#     command: >
#       mongosh --host lovalhost:27017 --eval 'rs.initiate({_id: "my-mongo-set", members: [{ _id : 0, host : "mongo1:27017" },{ _id : 1, host : "mongo2:27017" },{ _id : 2, host : "mongo3:27017" }]})' && mongod --replSet my-mongo-set --bind_ip_all --port 27017 

# networks:
#   default:
#     driver: bridge
